export default {
  document: {
    references: 'Referenzen',
  },
  shop: "Shop",
  content: "Inhalt",
  products: "Produkte",
  product: "Produkt",
  productVariants: "Produktvarianten",
  orders: "Bestellungen",
  users: "Kunden",
  tags: "Tags",
  variantOptionGroups: "Optionengruppen",
  variantOptions: "Optionen",
  manufacturers: "Hersteller",
  page: "Seite",
  pages: "Seiten",
  post: "Beitrag",
  posts: "Beiträge",
  blog: "Blog",
  menus: "Menüs",
  drafts: "Entwürfe",
  allDrafts: "Alle Entwürfe",
  categories: "Kategorien",
  customerGroups: "Kundengruppen",
  marketing: "Marketing",
  vouchers: "Gutscheine",
  shippingCountries: "Versand",
  editCategory: "Kategorie bearbeiten",
  settings: {
    title: "Einstellungen",
    homePage: "Startseite",
    general: "Allgemeines",
  },
  structure: "Struktur",
  order: {
    views: {
      overview: "Übersicht",
      edit: "Bearbeiten",
    },
  },
  widgets: {
    openOrders: "Offene Bestellungen",
    lastEdited: "Zuletzt bearbeitet",
    drafts: "Entwürfe",
    inactiveProducts: "Inaktive Produkte",
    inactiveProductVariants: "Inaktive Produktvarianten",
  },
  liveEditor: "Live Editor",
}