export default {
  shop: "Shop",
  website: "Webseite",
  content: "Inhalt",
  // products: "Produkte",
  product: "Produkte",
  productVariant: "Produktvarianten",
  order: "Bestellungen",
  user: "Kunden",
  users: "Kunden",
  tag: "Tags",
  variantOptionGroup: "Optionengruppen",
  variantOption: "Optionen",
  manufacturer: "Hersteller",
  // page: "Seite",
  page: "Seiten",
  // post: "Beitrag",
  post: "Beiträge",
  blog: "Blog",
  menu: "Menüs",
  drafts: "Entwürfe",
  allDrafts: "Alle Entwürfe",
  category_single: "Kategorie",
  category: "Kategorien",
  categories: "Kategorien",
  customerGroup: "Kundengruppen",
  marketing: "Marketing",
  voucher: "Gutscheine",
  shippingCountry: "Versand",
  settings: "Einstellungen",
  settingsGroup: "Allgemeines",
  settingsasdf: {
    title: "Einstellungen",
    homePage: "Startseite",
    general: "Allgemeines",
  },
  structure: "Struktur",
  actions: {
    editType: "{{type}} bearbeiten",
  },
  views: {
    titles: {
      overview: "Übersicht",
      edit: "Bearbeiten",
      references: 'Referenzen',
    },
  },
  widgets: {
    openOrders: "Offene Bestellungen",
    lastEdited: "Zuletzt bearbeitet",
    drafts: "Entwürfe",
    inactiveProducts: "Inaktive Produkte",
    inactiveProductVariants: "Inaktive Produktvarianten",
  },
  liveEditor: "Live Editor",
}