export default {
  document: {
    references: 'References',
  },
  shop: "Shop",
  content: "Content",
  products: "Products",
  product: "Product",
  productVariants: "Product Variants",
  orders: "Orders",
  users: "Customers",
  tags: "Tags",
  variantOptionGroups: "Option Groups",
  variantOptions: "Options",
  manufacturers: "Manufacturers",
  page: "Page",
  pages: "Pages",
  post: "Blog Post",
  posts: "Blog Posts",
  blog: "Blog",
  menus: "Menus",
  drafts: "Drafts",
  allDrafts: "All Drafts",
  categories: "Categories",
  customerGroups: "Customer Groups",
  marketing: "Marketing",
  vouchers: "Vouchers",
  shippingCountries: "Shipping",
  editCategory: "Edit Category",
  settings: {
    title: "Settings",
    homePage: "Home Page",
    general: "General",
  },
  structure: "Structure",
  order: {
    views: {
      overview: "Overview",
      edit: "Edit",
    },
  },
  widgets: {
    openOrders: "Open Orders",
    lastEdited: "Last Edited",
    drafts: "Drafts",
    inactiveProducts: "Inactive Products",
    inactiveProductVariants: "Inactive Product Variants",
  },
  liveEditor: "Live Editor",
}