/* eslint-disable @typescript-eslint/naming-convention, camelcase */
export default {
  structure: { title: 'Structure' },
  content: { title: 'Content' },

  website: { title: 'Website' },
  page: { title: 'Pages' },
  post: { title: 'Posts' },
  menu: { title: 'Menus' },

  shop: { title: 'Shop' },
  order: { title: 'Orders' },
  orderMeta: { title: 'Orders (Temporary)' },
  products: {
    title: 'Products',
    productContainer: 'Product data',
    edit: 'Edit product',
    variant: 'Variant',
    variants: 'Variants',
    addVariant: 'New variant',
    kinds: {
      title: 'Product kinds',
      list: {
        all: 'All',
        wine: 'Wines',
        physical: 'Other',
        digital: 'Digital',
        bundle: 'Bundles',
      },
    },
  },
  productVariant: {
    title: 'Product variants',
  },
  variantOptions: {
    title: 'Option groups',
    group: 'Option group',
    groups: 'Option groups',
    option: 'Option',
    options: 'Options',
  },
  categories: { title: 'Categories' },
  manufacturer: { title: 'Manufacturers' },
  customer: { title: 'Customers' },
  customers: { title: 'Customers' },
  customerGroup: { title: 'Customer groups' },
  customerGroups: { title: 'Customer groups' },
  settingsGroup: { title: 'Settings' },
  shopSettingsGroup: { title: 'Shop settings' },
  settings: { title: 'General' },
  shopSettings: { title: 'General' },
  shippingMethod: { title: 'Shipping methods' },
  taxCountry: { title: 'Countries' },
  taxCategory: { title: 'Tax categories' },
  voucher: { title: 'Vouchers' },
  coupon: { title: 'Coupons' },
  blog: { title: 'Blog' },

  tag: 'Tags',
  // page: "Page",
  allDrafts: 'All drafts',
  category_single: 'Category',
  category: 'Categories',
  marketing: 'Marketing',
  shippingCountry: 'Shipping',
  settingsasdf: {
    title: 'Settings',
    homePage: 'Home page',
    general: 'General',
  },

  actions: {
    editType: 'Edit {{type}}',
  },
  views: {
    titles: {
      overview: 'Overview',
      edit: 'Edit',
      references: 'References',
    },
  },
  widgets: {
    openOrders: 'Open orders',
    lastEdited: 'Last edited',
    drafts: 'Drafts',
    inactiveProducts: 'Inactive products',
    inactiveProductVariants: 'Inactive product variants',
  },
  liveEditor: 'Live Editor',
}
