/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type Voucher = {
  _id: string
  _type: 'voucher'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InternationalizedArrayString
}

export type InternationalizedArrayString = Array<
  {
    _key: string
  } & InternationalizedArrayStringValue
>

export type VariantOptionGroupReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'variantOptionGroup'
}

export type VariantOption = {
  _id: string
  _type: 'variantOption'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InternationalizedArrayString
  group?: VariantOptionGroupReference
  sortOrder?: number
}

export type VariantOptionGroup = {
  _id: string
  _type: 'variantOptionGroup'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InternationalizedArrayString
  displayMode?: 'dropdown' | 'list'
  sortOrder?: number
}

export type TaxCountryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'taxCountry'
}

export type TaxCategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'taxCategory'
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type ShopSettings = {
  _id: string
  _type: 'shopSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  billingAddress?: BusinessAddress
  bankAccount?: BankAccount
  lastInvoiceNumber?: number
  orderNumberPrefix?: string
  invoiceNumberPrefix?: string
  defaultCountry?: TaxCountryReference
  freeShippingCalculation?: 'beforeDiscount' | 'afterDiscount'
  returnAddress?: BusinessAddress
  returnShippingBorneBy?: 'customer' | 'merchant'
  returnPolicyNote?: InternationalizedArrayText
  defaultTaxCategory?: TaxCategoryReference
  stockThreshold?: number
  shopPage?: PageReference
  termsPage?: PageReference
  withdrawalPolicyPage?: PageReference
  filters?: Array<
    | {
        field?: 'price' | 'category'
        _type: 'productFieldFilter'
        _key: string
      }
    | {
        field?: 'vintage' | 'varietal' | 'color' | 'classification' | 'qualityGrade' | 'volume'
        _type: 'wineFieldFilter'
        _key: string
      }
    | ({
        _key: string
      } & VariantOptionGroupReference)
  >
}

export type InternationalizedArrayText = Array<
  {
    _key: string
  } & InternationalizedArrayTextValue
>

export type BusinessAddress = {
  _type: 'businessAddress'
  line1?: string
  line2?: string
  zip?: string
  city?: InternationalizedArrayString
  country?:
    | 'AD'
    | 'AL'
    | 'AT'
    | 'AX'
    | 'BA'
    | 'BE'
    | 'BG'
    | 'BY'
    | 'CH'
    | 'CY'
    | 'CZ'
    | 'DE'
    | 'DK'
    | 'EE'
    | 'ES'
    | 'FI'
    | 'FO'
    | 'FR'
    | 'GB'
    | 'GG'
    | 'GI'
    | 'GR'
    | 'HR'
    | 'HU'
    | 'IE'
    | 'IM'
    | 'IS'
    | 'IT'
    | 'JE'
    | 'LI'
    | 'LT'
    | 'LU'
    | 'LV'
    | 'MC'
    | 'MD'
    | 'ME'
    | 'MK'
    | 'MT'
    | 'NL'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'RS'
    | 'SE'
    | 'SI'
    | 'SJ'
    | 'SK'
    | 'SM'
    | 'UA'
    | 'VA'
    | 'XK'
}

export type TaxCountry = {
  _id: string
  _type: 'taxCountry'
  _createdAt: string
  _updatedAt: string
  _rev: string
  enabled?: boolean
  countryCode?:
    | 'AD'
    | 'AL'
    | 'AT'
    | 'AX'
    | 'BA'
    | 'BE'
    | 'BG'
    | 'BY'
    | 'CH'
    | 'CY'
    | 'CZ'
    | 'DE'
    | 'DK'
    | 'EE'
    | 'ES'
    | 'FI'
    | 'FO'
    | 'FR'
    | 'GB'
    | 'GG'
    | 'GI'
    | 'GR'
    | 'HR'
    | 'HU'
    | 'IE'
    | 'IM'
    | 'IS'
    | 'IT'
    | 'JE'
    | 'LI'
    | 'LT'
    | 'LU'
    | 'LV'
    | 'MC'
    | 'MD'
    | 'ME'
    | 'MK'
    | 'MT'
    | 'NL'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'RS'
    | 'SE'
    | 'SI'
    | 'SJ'
    | 'SK'
    | 'SM'
    | 'UA'
    | 'VA'
    | 'XK'
  rules?: Array<
    {
      _key: string
    } & TaxRule
  >
}

export type BankAccount = {
  _type: 'bankAccount'
  name?: string
  bic?: string
  iban?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type MenuReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'menu'
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  siteTitle?: InternationalizedArrayString
  siteShortDescription?: InternationalizedArrayString
  defaultShareImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  homePage?: PageReference
  privacyPage?: PageReference
  mainMenus?: Array<
    {
      _key: string
    } & MenuReference
  >
  footerMenus?: Array<
    {
      _key: string
    } & MenuReference
  >
  senderName?: string
  senderEmail?: string
  gtmId?: string
  company?: Company
}

export type Company = {
  _type: 'company'
  name?: InternationalizedArrayString
  owner?: string
  address?: BusinessAddress
  email?: string
  phone?: string
  vatId?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type OrderReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'order'
}

export type OrderWithdrawal = {
  _id: string
  _type: 'orderWithdrawal'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRef?: OrderReference
  declaredAt?: string
  status?: 'received' | 'processing' | 'refunded' | 'rejected'
  reason?: string
  note?: string
}

export type OrderMeta = {
  _id: string
  _type: 'orderMeta'
  _createdAt: string
  _updatedAt: string
  _rev: string
  fulfillment?: Fulfillment
  customer?: OrderCustomer
  paymentIntentId?: string
  totals?: OrderTotals
  orderItems?: Array<
    {
      _key: string
    } & OrderItem
  >
  appliedCoupons?: Array<
    {
      _key: string
    } & AppliedCoupon
  >
}

export type OrderTotals = {
  _type: 'orderTotals'
  grandTotal?: number
  subtotal?: number
  shipping?: number
  discount?: number
  totalVat?: number
  vatBreakdown?: Array<
    {
      _key: string
    } & VatBreakdownItem
  >
  currency?: 'EUR'
}

export type OrderCustomer = {
  _type: 'orderCustomer'
  contactEmail?: string
  locale?: 'en' | 'de'
  supabaseId?: string
  billingAddress?: AddressStrict
  shippingAddress?: AddressStrict
}

export type ShippingMethodReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'shippingMethod'
}

export type Fulfillment = {
  _type: 'fulfillment'
  trackingCode?: string
  pickupLocation?: string
  methodTitle?: string
  methodType?: 'delivery' | 'pickup'
  shippingCost?: number
  taxSnapshot?: VatBreakdownItem
  packagingLines?: Array<
    {
      _key: string
    } & FulfillmentPackagingLine
  >
  method?: ShippingMethodReference
}

export type Order = {
  _id: string
  _type: 'order'
  _createdAt: string
  _updatedAt: string
  _rev: string
  fulfillment?: Fulfillment
  customer?: OrderCustomer
  paymentIntentId?: string
  totals?: OrderTotals
  orderItems?: Array<
    {
      _key: string
    } & OrderItem
  >
  appliedCoupons?: Array<
    {
      _key: string
    } & AppliedCoupon
  >
  orderNumber?: string
  invoiceNumber?: string
  status?: 'created' | 'processing' | 'shipped' | 'delivered' | 'canceled' | 'returned'
  paymentStatus?: 'succeeded' | 'refunded' | 'partiallyRefunded'
  statusHistory?: Array<
    {
      _key: string
    } & OrderStatusHistory
  >
}

export type NewsletterSubscriber = {
  _id: string
  _type: 'newsletterSubscriber'
  _createdAt: string
  _updatedAt: string
  _rev: string
  email?: string
  locale?: 'en' | 'de'
  status?: 'pending' | 'confirmed' | 'unsubscribed'
  source?: 'standalone' | 'registration'
  token?: string
  supabaseId?: string
  confirmedAt?: string
}

export type Menu = {
  _id: string
  _type: 'menu'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InternationalizedArrayString
  items?: Array<
    {
      _key: string
    } & MenuItem
  >
}

export type Manufacturer = {
  _id: string
  _type: 'manufacturer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: InternationalizedArrayString
  description?: InternationalizedArrayText
  link?: string
}

export type CustomerGroup = {
  _id: string
  _type: 'customerGroup'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InternationalizedArrayString
}

export type CustomerGroupReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'customerGroup'
}

export type Customer = {
  _id: string
  _type: 'customer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  email?: string
  locale?: 'en' | 'de'
  customerNumber?: string
  customerGroups?: Array<
    {
      _key: string
    } & CustomerGroupReference
  >
  supabaseId?: string
  status?: 'registered' | 'invited' | 'active'
  address?: Address
}

export type Address = {
  _type: 'address'
  prename?: string
  lastname?: string
  line1?: string
  line2?: string
  zip?: string
  city?: InternationalizedArrayString
  country?:
    | 'AD'
    | 'AL'
    | 'AT'
    | 'AX'
    | 'BA'
    | 'BE'
    | 'BG'
    | 'BY'
    | 'CH'
    | 'CY'
    | 'CZ'
    | 'DE'
    | 'DK'
    | 'EE'
    | 'ES'
    | 'FI'
    | 'FO'
    | 'FR'
    | 'GB'
    | 'GG'
    | 'GI'
    | 'GR'
    | 'HR'
    | 'HU'
    | 'IE'
    | 'IM'
    | 'IS'
    | 'IT'
    | 'JE'
    | 'LI'
    | 'LT'
    | 'LU'
    | 'LV'
    | 'MC'
    | 'MD'
    | 'ME'
    | 'MK'
    | 'MT'
    | 'NL'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'RS'
    | 'SE'
    | 'SI'
    | 'SJ'
    | 'SK'
    | 'SM'
    | 'UA'
    | 'VA'
    | 'XK'
  state?: string
  phone?: string
}

export type Youtube = {
  _type: 'youtube'
  url?: string
  showControls?: boolean
  autoload?: boolean
  autopause?: boolean
  start?: string
}

export type Wine = {
  _type: 'wine'
  vinofactWineId?: string
  volume?:
    | 100
    | 187
    | 200
    | 250
    | 375
    | 500
    | 750
    | 1000
    | 1500
    | 2000
    | 2250
    | 3000
    | 4500
    | 5000
    | 6000
    | 9000
    | 12000
    | 15000
  vintage?: string
}

export type VatBreakdownItem = {
  _type: 'vatBreakdownItem'
  rate?: number
  net?: number
  vat?: number
}

export type TaxRule = {
  _type: 'taxRule'
  taxCategory?: TaxCategoryReference
  rate?: number
}

export type WinePackagingConfig = {
  _type: 'winePackagingConfig'
  volume?:
    | 100
    | 187
    | 200
    | 250
    | 375
    | 500
    | 750
    | 1000
    | 1500
    | 2000
    | 2250
    | 3000
    | 4500
    | 5000
    | 6000
    | 9000
    | 12000
    | 15000
  packages?: Array<
    {
      _key: string
    } & WinePackage
  >
}

export type WinePackage = {
  _type: 'winePackage'
  count?: number
  price?: number
}

export type ShippingRate = {
  _type: 'shippingRate'
  maxWeight?: number
  price?: number
}

export type Seo = {
  _type: 'seo'
  metaTitle?: InternationalizedArrayString
  metaDescription?: InternationalizedArrayString
  shareTitle?: InternationalizedArrayString
  shareDescription?: InternationalizedArrayString
  shareImage?: LocaleAltImage
}

export type OrderStatusHistory = {
  _type: 'orderStatusHistory'
  type?: 'payment' | 'fulfillment'
  status?: string
  timestamp?: string
  source?: string
  note?: string
}

export type OrderItemWine = {
  _type: 'orderItemWine'
  vintage?: string
  volume?: number
}

export type OrderItemOption = {
  _type: 'orderItemOption'
  groupTitle?: string
  optionTitle?: string
}

export type OrderItemBundle = {
  _type: 'orderItemBundle'
  itemCount?: number
}

export type OrderItem = {
  _type: 'orderItem'
  kind?: 'wine' | 'physical' | 'digital' | 'bundle'
  variantId?: string
  productId?: string
  parentId?: string
  title?: string
  subtitle?: string
  weight?: number
  sku?: string
  quantity?: number
  price?: number
  vatRate?: number
  vatAmount?: number
  packed?: boolean
  wine?: OrderItemWine
  options?: Array<
    {
      _key: string
    } & OrderItemOption
  >
  bundle?: OrderItemBundle
}

export type AddressStrict = {
  _type: 'addressStrict'
  name?: string
  prename?: string
  lastname?: string
  line1?: string
  line2?: string
  zip?: string
  city?: string
  country?:
    | 'AD'
    | 'AL'
    | 'AT'
    | 'AX'
    | 'BA'
    | 'BE'
    | 'BG'
    | 'BY'
    | 'CH'
    | 'CY'
    | 'CZ'
    | 'DE'
    | 'DK'
    | 'EE'
    | 'ES'
    | 'FI'
    | 'FO'
    | 'FR'
    | 'GB'
    | 'GG'
    | 'GI'
    | 'GR'
    | 'HR'
    | 'HU'
    | 'IE'
    | 'IM'
    | 'IS'
    | 'IT'
    | 'JE'
    | 'LI'
    | 'LT'
    | 'LU'
    | 'LV'
    | 'MC'
    | 'MD'
    | 'ME'
    | 'MK'
    | 'MT'
    | 'NL'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'RS'
    | 'SE'
    | 'SI'
    | 'SJ'
    | 'SK'
    | 'SM'
    | 'UA'
    | 'VA'
    | 'XK'
  state?: string
  phone?: string
}

export type CouponReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'coupon'
}

export type AppliedCoupon = {
  _type: 'appliedCoupon'
  couponRef?: CouponReference
  code?: string
  discountType?: 'percent' | 'fixed' | 'freeShipping'
  value?: number
  discountAmount?: number
}

export type Coupon = {
  _id: string
  _type: 'coupon'
  _createdAt: string
  _updatedAt: string
  _rev: string
  code?: string
  title?: InternationalizedArrayString
  description?: InternationalizedArrayText
  enabled?: boolean
  discountType?: 'percent' | 'fixed' | 'freeShipping'
  value?: number
  validFrom?: string
  validTo?: string
  minSubtotal?: number
  maxRedemptions?: number
  redemptionCount?: number
}

export type ProductVariantReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'productVariant'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type BlogReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'blog'
}

export type MenuItem = {
  _type: 'menuItem'
  title?: InternationalizedArrayString
  linkType?: 'internal' | 'external'
  internalLinkReference?:
    ProductVariantReference | PageReference | PostReference | CategoryReference | BlogReference
  url?: InternationalizedArrayUrl
}

export type InternationalizedArrayUrl = Array<
  {
    _key: string
  } & InternationalizedArrayUrlValue
>

export type LocaleImage = {
  _type: 'localeImage'
  image?: InternationalizedArrayCropImage
  alt?: InternationalizedArrayString
}

export type InternationalizedArrayCropImage = Array<
  {
    _key: string
  } & InternationalizedArrayCropImageValue
>

export type LocaleAltImage = {
  _type: 'localeAltImage'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: InternationalizedArrayString
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type GeneratedZip = {
  _type: 'generatedZip'
  file?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  hash?: string
  generatedAt?: string
  staleAssetIds?: Array<string>
}

export type FulfillmentPackagingLine = {
  _type: 'fulfillmentPackagingLine'
  volume?: number
  packSize?: number
  quantity?: number
  price?: number
}

export type ShippingMethod = {
  _id: string
  _type: 'shippingMethod'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InternationalizedArrayString
  methodType?: 'delivery'
  eligibleCountries?: Array<
    {
      _key: string
    } & TaxCountryReference
  >
  rates?: Array<
    {
      _key: string
    } & ShippingRate
  >
  packagingConfigs?: Array<
    {
      _key: string
    } & WinePackagingConfig
  >
  freeShippingThreshold?: number
}

export type CropImage = {
  _type: 'cropImage'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
}

export type InternalLink = {
  _type: 'internalLink'
  internalLinkTitle?: InternationalizedArrayString
  internalLinkReference?:
    ProductVariantReference | PageReference | PostReference | CategoryReference | BlogReference
  internalLinkDisplayType?: 'link' | 'button' | 'ghost'
}

export type Blog = {
  _id: string
  _type: 'blog'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InternationalizedArrayString
  description?: InternationalizedArrayString
  seo?: Seo
  postsPerPage?: number
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InternationalizedArrayString
  description?: InternationalizedArrayString
  sortOrder?: number
  level?: number
  parent?: CategoryReference
  filters?: Array<
    | {
        field?: 'price' | 'category'
        _type: 'productFieldFilter'
        _key: string
      }
    | {
        field?: 'vintage' | 'varietal' | 'color' | 'classification' | 'qualityGrade' | 'volume'
        _type: 'wineFieldFilter'
        _key: string
      }
    | ({
        _key: string
      } & VariantOptionGroupReference)
  >
  seo?: Seo
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InternationalizedArrayString
  slug?: InternationalizedArraySlug
  publishedAt?: string
  seo?: Seo
}

export type InternationalizedArraySlug = Array<
  {
    _key: string
  } & InternationalizedArraySlugValue
>

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InternationalizedArrayString
  slug?: InternationalizedArraySlug
  seo?: Seo
}

export type ProductReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'product'
}

export type ProductList = {
  _type: 'productList'
  title?: InternationalizedArrayString
  filters?: Array<
    | {
        field?: 'price' | 'category'
        _type: 'productFieldFilter'
        _key: string
      }
    | {
        field?: 'vintage' | 'varietal' | 'color' | 'classification' | 'qualityGrade' | 'volume'
        _type: 'wineFieldFilter'
        _key: string
      }
    | ({
        _key: string
      } & VariantOptionGroupReference)
  >
  products?: Array<
    {
      _key: string
    } & ProductReference
  >
  disabled?: boolean
}

export type ProductVariantList = {
  _type: 'productVariantList'
  title?: InternationalizedArrayString
  products?: Array<
    {
      _key: string
    } & ProductVariantReference
  >
  disabled?: boolean
}

export type CategoryList = {
  _type: 'categoryList'
  title?: InternationalizedArrayString
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
  disabled?: boolean
}

export type Carousel = {
  _type: 'carousel'
  slides?: Array<
    {
      _key: string
    } & LocaleAltImage
  >
  autoplay?: boolean
  autoplayDelay?: number
  loop?: boolean
  fade?: boolean
  preload?: boolean
}

export type BundleItem = {
  _type: 'bundleItem'
  quantity?: number
  product?: ProductVariantReference
}

export type VariantOptionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'variantOption'
}

export type ManufacturerReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'manufacturer'
}

export type ProductVariant = {
  _id: string
  _type: 'productVariant'
  _createdAt: string
  _updatedAt: string
  _rev: string
  status?: 'active' | 'comingSoon' | 'soldOut' | 'archived'
  options?: Array<
    {
      _key: string
    } & VariantOptionReference
  >
  wine?: Wine
  weight?: number
  bundleItems?: Array<
    {
      _key: string
    } & BundleItem
  >
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
  kind?: 'wine' | 'physical' | 'digital' | 'bundle'
  manufacturers?: Array<
    {
      _key: string
    } & ManufacturerReference
  >
  title?: InternationalizedArrayString
  product?: ProductReference
  sku?: string
  taxCategory?: TaxCategoryReference
  price?: number
  compareAtPrice?: number
  image?: LocaleAltImage
  seo?: Seo
  stock?: number
  stockThreshold?: number
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InternationalizedArrayString
  kind?: 'wine' | 'physical' | 'digital' | 'bundle'
  weight?: number
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
  manufacturers?: Array<
    {
      _key: string
    } & ManufacturerReference
  >
  taxCategory?: TaxCategoryReference
  price?: number
  compareAtPrice?: number
  image?: LocaleAltImage
  seo?: Seo
}

export type TaxCategory = {
  _id: string
  _type: 'taxCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InternationalizedArrayString
  code?: Slug
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type BaseImage = {
  _type: 'baseImage'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference?: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message?: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type MediaFolderReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'media.folder'
}

export type MediaFolder = {
  _id: string
  _type: 'media.folder'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  parent?: MediaFolderReference
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type InternationalizedArrayBaseImageValue = {
  _type: 'internationalizedArrayBaseImageValue'
  value?: BaseImage
  language?: string
}

export type InternationalizedArrayCropImageValue = {
  _type: 'internationalizedArrayCropImageValue'
  value?: CropImage
  language?: string
}

export type InternationalizedArraySlugValue = {
  _type: 'internationalizedArraySlugValue'
  value?: Slug
  language?: string
}

export type InternationalizedArrayTextValue = {
  _type: 'internationalizedArrayTextValue'
  value?: string
  language?: string
}

export type InternationalizedArrayUrlValue = {
  _type: 'internationalizedArrayUrlValue'
  value?: string
  language?: string
}

export type InternationalizedArrayStringValue = {
  _type: 'internationalizedArrayStringValue'
  value?: string
  language?: string
}

export type InternationalizedArrayBaseImage = Array<
  {
    _key: string
  } & InternationalizedArrayBaseImageValue
>

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Voucher
  | InternationalizedArrayString
  | VariantOptionGroupReference
  | VariantOption
  | VariantOptionGroup
  | TaxCountryReference
  | TaxCategoryReference
  | PageReference
  | ShopSettings
  | InternationalizedArrayText
  | BusinessAddress
  | TaxCountry
  | BankAccount
  | SanityImageAssetReference
  | MenuReference
  | Settings
  | Company
  | SanityImageCrop
  | SanityImageHotspot
  | OrderReference
  | OrderWithdrawal
  | OrderMeta
  | OrderTotals
  | OrderCustomer
  | ShippingMethodReference
  | Fulfillment
  | Order
  | NewsletterSubscriber
  | Menu
  | Manufacturer
  | CustomerGroup
  | CustomerGroupReference
  | Customer
  | Address
  | Youtube
  | Wine
  | VatBreakdownItem
  | TaxRule
  | WinePackagingConfig
  | WinePackage
  | ShippingRate
  | Seo
  | OrderStatusHistory
  | OrderItemWine
  | OrderItemOption
  | OrderItemBundle
  | OrderItem
  | AddressStrict
  | CouponReference
  | AppliedCoupon
  | Coupon
  | ProductVariantReference
  | PostReference
  | CategoryReference
  | BlogReference
  | MenuItem
  | InternationalizedArrayUrl
  | LocaleImage
  | InternationalizedArrayCropImage
  | LocaleAltImage
  | SanityFileAssetReference
  | GeneratedZip
  | FulfillmentPackagingLine
  | ShippingMethod
  | CropImage
  | InternalLink
  | Blog
  | Category
  | Post
  | InternationalizedArraySlug
  | Page
  | ProductReference
  | ProductList
  | ProductVariantList
  | CategoryList
  | Carousel
  | BundleItem
  | VariantOptionReference
  | ManufacturerReference
  | ProductVariant
  | Product
  | TaxCategory
  | Slug
  | BaseImage
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | InternationalizedArrayBaseImageValue
  | InternationalizedArrayCropImageValue
  | InternationalizedArraySlugValue
  | InternationalizedArrayTextValue
  | InternationalizedArrayUrlValue
  | InternationalizedArrayStringValue
  | InternationalizedArrayBaseImage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
