/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Voucher = {
  _id: string;
  _type: "voucher";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type VariantOptionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "variantOption";
};

export type VariantOptionGroup = {
  _id: string;
  _type: "variantOptionGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  sortOrder?: number;
  options?: Array<
    {
      _key: string;
    } & VariantOptionReference
  >;
};

export type VariantOption = {
  _id: string;
  _type: "variantOption";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  sortOrder?: number;
  images?: Array<
    {
      _key: string;
    } & LocaleImage
  >;
};

export type TaxCountryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "taxCountry";
};

export type TaxCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "taxCategory";
};

export type ShopSettings = {
  _id: string;
  _type: "shopSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  defaultCountry?: TaxCountryReference;
  freeShippingCalculation?: "beforeDiscount" | "afterDiscount";
  stockThreshold?: number;
  defaultTaxCategory?: TaxCategoryReference;
  orderNumberPrefix?: string;
  invoiceNumberPrefix?: string;
  lastInvoiceNumber?: number;
  bankAccount?: BankAccount;
};

export type BankAccount = {
  _type: "bankAccount";
  name?: string;
  bic?: string;
  iban?: string;
};

export type TaxCountry = {
  _id: string;
  _type: "taxCountry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  enabled?: boolean;
  countryCode?:
    | "AD"
    | "AL"
    | "AT"
    | "AX"
    | "BA"
    | "BE"
    | "BG"
    | "BY"
    | "CH"
    | "CY"
    | "CZ"
    | "DE"
    | "DK"
    | "EE"
    | "ES"
    | "FI"
    | "FO"
    | "FR"
    | "GB"
    | "GG"
    | "GI"
    | "GR"
    | "HR"
    | "HU"
    | "IE"
    | "IM"
    | "IS"
    | "IT"
    | "JE"
    | "LI"
    | "LT"
    | "LU"
    | "LV"
    | "MC"
    | "MD"
    | "ME"
    | "MK"
    | "MT"
    | "NL"
    | "NO"
    | "PL"
    | "PT"
    | "RO"
    | "RS"
    | "SE"
    | "SI"
    | "SJ"
    | "SK"
    | "SM"
    | "UA"
    | "VA"
    | "XK";
  rules?: Array<
    {
      _key: string;
    } & TaxRule
  >;
};

export type ShippingMethod = {
  _id: string;
  _type: "shippingMethod";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  methodType?: "delivery" | "pickup";
  pickupFee?: number;
  eligibleCountries?: Array<
    {
      _key: string;
    } & TaxCountryReference
  >;
  rates?: Array<
    {
      _key: string;
    } & ShippingRate
  >;
  taxCategory?: TaxCategoryReference;
  freeShippingThreshold?: number;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type MenuReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "menu";
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: InternationalizedArrayString;
  siteShortDescription?: InternationalizedArrayString;
  siteDescription?: InternationalizedArrayText;
  homePage?: PageReference;
  privacyPage?: PageReference;
  mainMenus?: Array<
    {
      _key: string;
    } & MenuReference
  >;
  footerMenus?: Array<
    {
      _key: string;
    } & MenuReference
  >;
  gtmId?: string;
  company?: Company;
};

export type Company = {
  _type: "company";
  name?: InternationalizedArrayString;
  owner?: string;
  address?: Address;
};

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type ManufacturerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "manufacturer";
};

export type ProductBundle = {
  _id: string;
  _type: "productBundle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  price?: number;
  sku?: string;
  stock?: number;
  stockThreshold?: number;
  taxCategory?: TaxCategoryReference;
  images?: Array<
    {
      _key: string;
    } & LocaleImage
  >;
  compareAtPrice?: number;
  weight?: number;
  seo?: Seo;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  manufacturers?: Array<
    {
      _key: string;
    } & ManufacturerReference
  >;
  items?: Array<
    {
      _key: string;
    } & ProductBundleItem
  >;
};

export type Seo = {
  _type: "seo";
  metaTitle?: InternationalizedArrayString;
  metaDescription?: InternationalizedArrayString;
  shareTitle?: InternationalizedArrayString;
  shareDescription?: InternationalizedArrayString;
  shareImage?: InternationalizedArrayBaseImage;
  keywords?: InternationalizedArrayString;
};

export type OrderMeta = {
  _id: string;
  _type: "orderMeta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  paymentIntentId?: string;
  orderItems?: Array<
    {
      _key: string;
    } & OrderItem
  >;
  customer?: OrderCustomer;
  totals?: OrderTotals;
};

export type OrderTotals = {
  _type: "orderTotals";
  grandTotal?: number;
  subtotal?: number;
  shipping?: number;
  discount?: number;
  totalVat?: number;
};

export type OrderCustomer = {
  _type: "orderCustomer";
  locale?: "de" | "en";
  contactEmail?: string;
  supabaseId?: string;
  billingAddress?: AddressStrict;
  shippingAddress?: AddressStrict;
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoiceNumber?: string;
  status?:
    | "created"
    | "processing"
    | "shipped"
    | "delivered"
    | "canceled"
    | "returned";
  paymentStatus?: "succeeded" | "refunded" | "partiallyRefunded";
  statusHistory?: Array<
    {
      _key: string;
    } & OrderStatusHistory
  >;
  paymentIntentId?: string;
  orderItems?: Array<
    {
      _key: string;
    } & OrderItem
  >;
  customer?: OrderCustomer;
  totals?: OrderTotals;
};

export type Menu = {
  _id: string;
  _type: "menu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  items?: Array<
    {
      _key: string;
    } & MenuItem
  >;
};

export type Manufacturer = {
  _id: string;
  _type: "manufacturer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  link?: string;
  image?: InternationalizedArrayBaseImage;
};

export type InternationalizedArrayBaseImage = Array<
  {
    _key: string;
  } & InternationalizedArrayBaseImageValue
>;

export type CustomerGroup = {
  _id: string;
  _type: "customerGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
};

export type CustomerGroupReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "customerGroup";
};

export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  locale?: "de" | "en";
  receiveNewsletter?: boolean;
  customerNumber?: string;
  customerGroups?: Array<
    {
      _key: string;
    } & CustomerGroupReference
  >;
  supabaseId?: string;
  status?: "registered" | "invited" | "active";
  address?: Address;
};

export type Address = {
  _type: "address";
  prename?: string;
  lastname?: string;
  phone?: string;
  line1?: string;
  line2?: string;
  zip?: string;
  city?: InternationalizedArrayString;
  country?:
    | "AD"
    | "AL"
    | "AT"
    | "AX"
    | "BA"
    | "BE"
    | "BG"
    | "BY"
    | "CH"
    | "CY"
    | "CZ"
    | "DE"
    | "DK"
    | "EE"
    | "ES"
    | "FI"
    | "FO"
    | "FR"
    | "GB"
    | "GG"
    | "GI"
    | "GR"
    | "HR"
    | "HU"
    | "IE"
    | "IM"
    | "IS"
    | "IT"
    | "JE"
    | "LI"
    | "LT"
    | "LU"
    | "LV"
    | "MC"
    | "MD"
    | "ME"
    | "MK"
    | "MT"
    | "NL"
    | "NO"
    | "PL"
    | "PT"
    | "RO"
    | "RS"
    | "SE"
    | "SI"
    | "SJ"
    | "SK"
    | "SM"
    | "UA"
    | "VA"
    | "XK";
  state?: string;
};

export type PinwallReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pinwall";
};

export type PinwallModule = {
  _type: "pinwallModule";
  ctaReference?: PinwallReference;
  disabled?: boolean;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type ProductVariantReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "productVariant";
};

export type Pinwall = {
  _id: string;
  _type: "pinwall";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  entries?: Array<
    | ({
        _key: string;
      } & PinwallEntry)
    | ({
        _key: string;
      } & ProductReference)
    | ({
        _key: string;
      } & ProductVariantReference)
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type MenuItemImage = {
  _type: "menuItemImage";
  left?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  right?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imagePosition?: "center" | "top" | "bottom" | "left" | "right";
};

export type PinwallEntry = {
  _type: "pinwallEntry";
  layout?: "small" | "medium" | "large";
  top?: InternationalizedArrayString;
  center?: InternationalizedArrayString;
  bottom?: InternationalizedArrayString;
  links?: Array<
    | ({
        _key: string;
      } & ProductReference)
    | ({
        _key: string;
      } & ProductVariantReference)
  >;
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type TextBlock = {
  _type: "textBlock";
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          linkReference?: ProductReference | PageReference | PostReference;
          linkDisplayType?: "link" | "button" | "ghost";
          _type: "internalLink";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        linkReference?: ProductReference | PageReference | PostReference;
        linkDisplayType?: "link" | "button" | "ghost";
        _type: "internalLink";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Hero = {
  _type: "hero";
  title?: InternationalizedArrayString;
  bgImage?: InternationalizedArrayLocaleTextsImage;
  actions?: Array<{
    actionTitle?: InternationalizedArrayString;
    actionReference?: ProductReference | PageReference | PostReference;
    _type: "action";
    _key: string;
  }>;
};

export type AddressStrict = {
  _type: "addressStrict";
  name?: string;
  prename?: string;
  lastname?: string;
  phone?: string;
  line1?: string;
  line2?: string;
  zip?: string;
  city?: string;
  country?:
    | "AD"
    | "AL"
    | "AT"
    | "AX"
    | "BA"
    | "BE"
    | "BG"
    | "BY"
    | "CH"
    | "CY"
    | "CZ"
    | "DE"
    | "DK"
    | "EE"
    | "ES"
    | "FI"
    | "FO"
    | "FR"
    | "GB"
    | "GG"
    | "GI"
    | "GR"
    | "HR"
    | "HU"
    | "IE"
    | "IM"
    | "IS"
    | "IT"
    | "JE"
    | "LI"
    | "LT"
    | "LU"
    | "LV"
    | "MC"
    | "MD"
    | "ME"
    | "MK"
    | "MT"
    | "NL"
    | "NO"
    | "PL"
    | "PT"
    | "RO"
    | "RS"
    | "SE"
    | "SI"
    | "SJ"
    | "SK"
    | "SM"
    | "UA"
    | "VA"
    | "XK";
  state?: string;
};

export type OrderStatusHistory = {
  _type: "orderStatusHistory";
  type?: "payment" | "fulfillment";
  status?: string;
  timestamp?: string;
  source?: string;
  note?: string;
};

export type OrderItem = {
  _type: "orderItem";
  type?: "product" | "productVariant" | "productBundle";
  productId?: string;
  parentId?: string;
  productParentId?: string;
  title?: InternationalizedArrayString;
  variantTitle?: InternationalizedArrayString;
  quantity?: number;
  recipeQuantity?: number;
  price?: number;
  vatRate?: number;
  vatAmount?: number;
  packed?: boolean;
};

export type ImageArray = Array<
  {
    _key: string;
  } & BaseImage
>;

export type ShippingRate = {
  _type: "shippingRate";
  maxWeight?: number;
  price?: number;
};

export type TaxRule = {
  _type: "taxRule";
  taxCategory?: TaxCategoryReference;
  rate?: number;
  exciseDuty?: number;
};

export type InternalLink = {
  _type: "internalLink";
  linkTitle?: InternationalizedArrayString;
  linkReference?: ProductReference | PageReference | PostReference;
  linkDisplayType?: "link" | "button" | "ghost";
};

export type Carousel = {
  _type: "carousel";
  autoplay?: boolean;
  autoplayDelay?: number;
  loop?: boolean;
  fade?: boolean;
};

export type BlogReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blog";
};

export type MenuItem = {
  _type: "menuItem";
  title?: InternationalizedArrayString;
  linkType?: "internal" | "external" | "none";
  linkTitle?: InternationalizedArrayString;
  linkReference?:
    | ProductReference
    | ProductVariantReference
    | PageReference
    | PostReference
    | CategoryReference
    | BlogReference;
  url?: string;
  children?: Array<
    {
      _key: string;
    } & MenuItem
  >;
  images?: MenuItemImage;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  description?: InternationalizedArrayString;
  seo?: Seo;
  postsPerPage?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  description?: InternationalizedArrayString;
  level?: number;
  sortOrder?: number;
  parent?: CategoryReference;
  image?: LocaleImage;
  seo?: Seo;
};

export type LocaleImage = {
  _type: "localeImage";
  image?: InternationalizedArrayCropImage;
  title?: InternationalizedArrayString;
  alt?: InternationalizedArrayString;
};

export type Youtube = {
  _type: "youtube";
  url?: string;
  showControls?: boolean;
  autoload?: boolean;
  autopause?: boolean;
  start?: string;
};

export type CropImage = {
  _type: "cropImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
};

export type LocaleTextsImage = {
  _type: "localeTextsImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  title?: InternationalizedArrayString;
  alt?: InternationalizedArrayString;
};

export type BaseImage = {
  _type: "baseImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  title?: string;
  alt?: string;
};

export type ProductBundleItem = {
  _type: "productBundleItem";
  quantity?: number;
  product?: ProductReference | ProductVariantReference;
};

export type ProductVariant = {
  _id: string;
  _type: "productVariant";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  price?: number;
  vinofactWineId?: string;
  sku?: string;
  stock?: number;
  stockThreshold?: number;
  taxCategory?: TaxCategoryReference;
  images?: Array<
    {
      _key: string;
    } & LocaleImage
  >;
  compareAtPrice?: number;
  weight?: number;
  seo?: Seo;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  manufacturers?: Array<
    {
      _key: string;
    } & ManufacturerReference
  >;
  active?: boolean;
  options?: Array<
    {
      _key: string;
    } & VariantOptionReference
  >;
  featured?: boolean;
  coverImage?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InternationalizedArrayTextBlockValue = {
  _type: "internationalizedArrayTextBlockValue";
  value?: TextBlock;
};

export type InternationalizedArrayLocaleTextsImageValue = {
  _type: "internationalizedArrayLocaleTextsImageValue";
  value?: LocaleTextsImage;
};

export type InternationalizedArrayLocaleImageValue = {
  _type: "internationalizedArrayLocaleImageValue";
  value?: LocaleImage;
};

export type InternationalizedArrayBaseImageValue = {
  _type: "internationalizedArrayBaseImageValue";
  value?: BaseImage;
};

export type InternationalizedArrayCropImageValue = {
  _type: "internationalizedArrayCropImageValue";
  value?: CropImage;
};

export type InternationalizedArraySlugValue = {
  _type: "internationalizedArraySlugValue";
  value?: Slug;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
};

export type InternationalizedArrayTextBlock = Array<
  {
    _key: string;
  } & InternationalizedArrayTextBlockValue
>;

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: InternationalizedArraySlug;
  seo?: Seo;
  textili2?: InternationalizedArrayTextBlock;
  modules?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & TextBlock)
  >;
};

export type InternationalizedArrayLocaleTextsImage = Array<
  {
    _key: string;
  } & InternationalizedArrayLocaleTextsImageValue
>;

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
};

export type InternationalizedArraySlug = Array<
  {
    _key: string;
  } & InternationalizedArraySlugValue
>;

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  price?: number;
  vinofactWineId?: string;
  sku?: string;
  stock?: number;
  stockThreshold?: number;
  taxCategory?: TaxCategoryReference;
  images?: Array<
    {
      _key: string;
    } & LocaleImage
  >;
  compareAtPrice?: number;
  weight?: number;
  seo?: Seo;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  manufacturers?: Array<
    {
      _key: string;
    } & ManufacturerReference
  >;
  example?: Array<{
    title?: string;
    amount?: number;
    _type: "inline";
    _key: string;
  }>;
  variants?: Array<
    {
      _key: string;
    } & ProductVariantReference
  >;
};

export type TaxCategory = {
  _id: string;
  _type: "taxCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  code?: Slug;
};

export type InternationalizedArrayLocaleImage = Array<
  {
    _key: string;
  } & InternationalizedArrayLocaleImageValue
>;

export type InternationalizedArrayCropImage = Array<
  {
    _key: string;
  } & InternationalizedArrayCropImageValue
>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Voucher
  | InternationalizedArrayString
  | VariantOptionReference
  | VariantOptionGroup
  | VariantOption
  | TaxCountryReference
  | TaxCategoryReference
  | ShopSettings
  | BankAccount
  | TaxCountry
  | ShippingMethod
  | PageReference
  | MenuReference
  | Settings
  | Company
  | InternationalizedArrayText
  | CategoryReference
  | ManufacturerReference
  | ProductBundle
  | Seo
  | OrderMeta
  | OrderTotals
  | OrderCustomer
  | Order
  | Menu
  | Manufacturer
  | InternationalizedArrayBaseImage
  | CustomerGroup
  | CustomerGroupReference
  | Customer
  | Address
  | PinwallReference
  | PinwallModule
  | ProductReference
  | ProductVariantReference
  | Pinwall
  | SanityImageAssetReference
  | MenuItemImage
  | PinwallEntry
  | PostReference
  | TextBlock
  | PortableText
  | SanityImageCrop
  | SanityImageHotspot
  | Hero
  | AddressStrict
  | OrderStatusHistory
  | OrderItem
  | ImageArray
  | ShippingRate
  | TaxRule
  | InternalLink
  | Carousel
  | BlogReference
  | MenuItem
  | Blog
  | Category
  | LocaleImage
  | Youtube
  | CropImage
  | LocaleTextsImage
  | BaseImage
  | ProductBundleItem
  | ProductVariant
  | MediaTag
  | Slug
  | InternationalizedArrayTextBlockValue
  | InternationalizedArrayLocaleTextsImageValue
  | InternationalizedArrayLocaleImageValue
  | InternationalizedArrayBaseImageValue
  | InternationalizedArrayCropImageValue
  | InternationalizedArraySlugValue
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | InternationalizedArrayTextBlock
  | Page
  | InternationalizedArrayLocaleTextsImage
  | Post
  | InternationalizedArraySlug
  | Product
  | TaxCategory
  | InternationalizedArrayLocaleImage
  | InternationalizedArrayCropImage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;
